merge fix to - scientific functions linked to issue
itArnaudov/public pull request #8
Opened 2023-12-06 17:57 UTC by itArnaudov

tested in lab and confirm okay to merge code with main branch. thx

2023-12-06 18:00 UTC, Ivan-CBRE requested changes
please address the comments section, thanks.

2023-12-06 18:09 UTC, itArnaudov reviewed
all recommendations are done. thx

2023-12-06 18:09 UTC, itArnaudov commented on PY/calculator/readme.md
done. thx

2023-12-06 18:09 UTC, itArnaudov commented on PY/calculator/calc.py
completed. thx

2023-12-06 18:16 UTC, merged

2023-12-09 18:33 UTC, itArnaudov reviewed
ok

2023-12-09 18:34 UTC, itArnaudov reviewed
cool

2023-12-09 18:34 UTC, itArnaudov reviewed
approved

2023-12-09 18:34 UTC, itArnaudov reviewed
nice one

2023-12-09 18:35 UTC, itArnaudov reviewed
good

2023-12-09 18:35 UTC, itArnaudov reviewed
approved

2023-12-09 18:56 UTC, Ivan-CBRE reviewed
ok

2023-12-09 18:56 UTC, Ivan-CBRE reviewed
done

2023-12-09 18:56 UTC, Ivan-CBRE reviewed
accept

2023-12-09 18:56 UTC, Ivan-CBRE reviewed
good

2023-12-09 18:56 UTC, Ivan-CBRE reviewed
read

2023-12-09 18:56 UTC, Ivan-CBRE reviewed
good